import { useState } from "react";
import { useQueryClient } from "@tanstack/react-query";
import { useServerFn } from "@tanstack/react-start";
import { MarkdownView } from "./markdown-view";
import {
  approveSuggestion,
  dismissSuggestion,
  deleteSuggestionPermanently,
  reanalyzeMeetingSuggestion,
  reanalyzeMeetingSummary,
  reanalyzeMeetingSuggestionsList,
  type DemandSuggestion,
} from "@/lib/suggestions.functions";
import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsList, TabsTrigger, TabsContent } from "@/components/ui/tabs";
import { Textarea } from "@/components/ui/textarea";
import { toast } from "sonner";
import {
  Sparkles,
  CheckCircle2,
  FileText,
  ListTodo,
  Clock,
  Trash2,
  XCircle,
  ChevronDown,
  ChevronUp,
  Building2,
  Calendar,
  NotebookPen,
  RotateCcw,
} from "lucide-react";
import { cn } from "@/lib/utils";

interface MeetingDetailModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  suggestion: DemandSuggestion | null;
  allClientSuggestions?: DemandSuggestion[]; // All suggestions for this meeting/session if available
}

export function MeetingDetailModal({
  open,
  onOpenChange,
  suggestion,
  allClientSuggestions = [],
}: MeetingDetailModalProps) {
  const qc = useQueryClient();
  const approveFn = useServerFn(approveSuggestion);
  const dismissFn = useServerFn(dismissSuggestion);
  const deleteFn = useServerFn(deleteSuggestionPermanently);
  const reanalyzeSummaryFn = useServerFn(reanalyzeMeetingSummary);
  const reanalyzeSuggestionsFn = useServerFn(reanalyzeMeetingSuggestionsList);

  const [expandedSugId, setExpandedSugId] = useState<string | null>(
    suggestion?.id || null
  );
  const [isReanalyzingSummary, setIsReanalyzingSummary] = useState(false);
  const [isReanalyzingSuggestions, setIsReanalyzingSuggestions] = useState(false);

  if (!suggestion) return null;

  // Gather ONLY related suggestions generated by the EXACT SAME meeting session
  const relatedSuggestions =
    allClientSuggestions.length > 0
      ? allClientSuggestions.filter((s) => {
          if (s.client_id !== suggestion.client_id) return false;
          if (s.raw_content && suggestion.raw_content && s.raw_content === suggestion.raw_content) return true;
          if (s.ai_summary && suggestion.ai_summary && s.ai_summary === suggestion.ai_summary) return true;
          if (s.created_at && suggestion.created_at) {
            const diff = Math.abs(new Date(s.created_at).getTime() - new Date(suggestion.created_at).getTime());
            if (diff < 60000) return true;
          }
          return false;
        })
      : [suggestion];

  const handleApprove = async (sugId: string) => {
    try {
      await approveFn({ data: { id: sugId } });
      toast.success("Demanda criada como Rascunho!");
      qc.invalidateQueries({ queryKey: ["demands"] });
      qc.invalidateQueries({ queryKey: ["demand_suggestions"] });
    } catch (err: any) {
      toast.error("Erro ao criar demanda: " + err.message);
    }
  };

  const handleDismiss = async (sugId: string) => {
    try {
      await dismissFn({ data: { id: sugId } });
      toast.info("Sugestão descartada.");
      qc.invalidateQueries({ queryKey: ["demand_suggestions"] });
    } catch (err: any) {
      toast.error("Erro ao descartar: " + err.message);
    }
  };

  const handleDeletePermanently = async (sugId: string) => {
    if (!confirm("Tem certeza que deseja excluir permanentemente esta sugestão?")) return;
    try {
      await deleteFn({ data: { id: sugId } });
      toast.success("Sugestão excluída permanentemente.");
      qc.invalidateQueries({ queryKey: ["demand_suggestions"] });
      onOpenChange(false);
    } catch (err: any) {
      toast.error("Erro ao excluir: " + err.message);
    }
  };

  const handleReanalyzeSummary = async () => {
    setIsReanalyzingSummary(true);
    try {
      const geminiKey = (import.meta as any).env?.VITE_GEMINI_API_KEY || "";
      await reanalyzeSummaryFn({
        data: {
          suggestionId: suggestion.id,
          clientApiKey: geminiKey || undefined,
        },
      });
      toast.success("Resumo/Ata regerado com IA com sucesso!");
      qc.invalidateQueries({ queryKey: ["demand_suggestions"] });
    } catch (err: any) {
      toast.error("Erro ao regerar resumo: " + err.message);
    } finally {
      setIsReanalyzingSummary(false);
    }
  };

  const handleReanalyzeSuggestions = async () => {
    setIsReanalyzingSuggestions(true);
    try {
      const geminiKey = (import.meta as any).env?.VITE_GEMINI_API_KEY || "";
      await reanalyzeSuggestionsFn({
        data: {
          suggestionId: suggestion.id,
          clientApiKey: geminiKey || undefined,
        },
      });
      toast.success("Sugestões de demandas regeradas com IA!");
      qc.invalidateQueries({ queryKey: ["demand_suggestions"] });
    } catch (err: any) {
      toast.error("Erro ao regerar sugestões: " + err.message);
    } finally {
      setIsReanalyzingSuggestions(false);
    }
  };

  const clientName = suggestion.clients?.name || "Cliente";
  const ataContent = suggestion.ai_summary || "Nenhuma ata disponível.";
  const transcriptContent = suggestion.raw_content || "Nenhuma transcrição gravada.";

  // Extract manual notes if recorded in transcript
  let manualNotesText = "";
  if (transcriptContent) {
    const notesMatch = transcriptContent.match(/\[.*? — Anotações\]:\s*([\s\S]*?)(?=\n\n\[|$)/i);
    if (notesMatch && notesMatch[1]) {
      manualNotesText = notesMatch[1].trim();
    }
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-4xl h-[85vh] bg-[#18181b] border-white/10 text-foreground overflow-hidden flex flex-col p-6">
        
        {/* Header */}
        <DialogHeader className="shrink-0 pb-3 border-b border-white/10">
          <div className="flex items-center justify-between gap-3">
            <div className="flex items-center gap-2">
              <div className="p-2 rounded-xl bg-purple-500/20 text-purple-400 border border-purple-500/30">
                <FileText className="h-5 w-5" />
              </div>
              <div>
                <DialogTitle className="text-base font-bold text-zinc-100">
                  {suggestion.suggested_title}
                </DialogTitle>
                <div className="flex items-center gap-2 text-xs text-muted-foreground mt-0.5">
                  <span className="flex items-center gap-1 text-purple-300">
                    <Building2 className="h-3 w-3" /> {clientName}
                  </span>
                  <span>•</span>
                  <span className="flex items-center gap-1 font-mono">
                    <Calendar className="h-3 w-3" />
                    {new Date(suggestion.created_at).toLocaleDateString("pt-BR", {
                      day: "2-digit",
                      month: "2-digit",
                      hour: "2-digit",
                      minute: "2-digit",
                    })}
                  </span>
                </div>
              </div>
            </div>

            <div>
              {suggestion.status === "dismissed" && (
                <Button
                  variant="destructive"
                  size="sm"
                  onClick={() => handleDeletePermanently(suggestion.id)}
                  className="h-8 text-xs gap-1.5 font-semibold bg-red-600/20 text-red-300 hover:bg-red-600 hover:text-white border border-red-500/30 cursor-pointer"
                >
                  <Trash2 className="h-3.5 w-3.5" /> Excluir Permanentemente
                </Button>
              )}
            </div>
          </div>
        </DialogHeader>

        {/* Content Tabs */}
        <Tabs defaultValue="summary" className="flex-1 flex flex-col min-h-0 mt-2">
          <TabsList className="grid grid-cols-4 bg-zinc-900 border border-white/10 shrink-0">
            <TabsTrigger value="summary" className="text-xs gap-1.5 cursor-pointer">
              <Sparkles className="h-3.5 w-3.5 text-purple-400" /> Ata da Reunião
            </TabsTrigger>
            <TabsTrigger value="suggestions" className="text-xs gap-1.5 cursor-pointer">
              <ListTodo className="h-3.5 w-3.5 text-emerald-400" /> Sugestões ({relatedSuggestions.length})
            </TabsTrigger>
            <TabsTrigger value="notes" className="text-xs gap-1.5 cursor-pointer">
              <NotebookPen className="h-3.5 w-3.5 text-amber-400" /> Anotações
            </TabsTrigger>
            <TabsTrigger value="transcript" className="text-xs gap-1.5 cursor-pointer">
              <FileText className="h-3.5 w-3.5" /> Transcrição Bruta
            </TabsTrigger>
          </TabsList>

          {/* 1. ATA DA REUNIÃO (Resumo Executivo Formatado) */}
          <TabsContent value="summary" className="flex-1 min-h-0 mt-3 overflow-y-auto">
            <div className="h-full rounded-xl bg-black/40 border border-white/10 p-5 flex flex-col font-sans leading-relaxed overflow-y-auto space-y-3">
              <div className="flex items-center justify-between border-b border-white/10 pb-3 shrink-0">
                <h3 className="text-sm font-bold text-purple-300 flex items-center gap-2">
                  <Sparkles className="h-4 w-4" /> Ata Estruturada da Reunião
                </h3>
                <Button
                  variant="outline"
                  size="sm"
                  onClick={handleReanalyzeSummary}
                  disabled={isReanalyzingSummary}
                  className="h-7 text-xs font-semibold border-purple-500/30 bg-purple-500/10 text-purple-300 hover:bg-purple-500/20 gap-1.5 cursor-pointer"
                >
                  <RotateCcw className={cn("h-3.5 w-3.5", isReanalyzingSummary && "animate-spin")} />
                  {isReanalyzingSummary ? "Regerando Ata..." : "Refazer Resumo IA"}
                </Button>
              </div>
              <div className="w-full flex-1 overflow-y-auto pr-1">
                <MarkdownView content={ataContent} />
              </div>
            </div>
          </TabsContent>

          {/* 2. SUGESTÕES DE DEMANDAS (Lista com Briefings Detalhados) */}
          <TabsContent value="suggestions" className="flex-1 min-h-0 mt-3 overflow-y-auto space-y-3">
            <div className="flex items-center justify-between border-b border-white/10 pb-3 shrink-0">
              <h3 className="text-sm font-bold text-emerald-300 flex items-center gap-2">
                <ListTodo className="h-4 w-4" /> Sugestões de Demandas ({relatedSuggestions.length})
              </h3>
              <Button
                variant="outline"
                size="sm"
                onClick={handleReanalyzeSuggestions}
                disabled={isReanalyzingSuggestions}
                className="h-7 text-xs font-semibold border-emerald-500/30 bg-emerald-500/10 text-emerald-300 hover:bg-emerald-500/20 gap-1.5 cursor-pointer"
              >
                <RotateCcw className={cn("h-3.5 w-3.5", isReanalyzingSuggestions && "animate-spin")} />
                {isReanalyzingSuggestions ? "Regerando Sugestões..." : "Refazer Sugestões IA"}
              </Button>
            </div>
            {relatedSuggestions.length === 0 ? (
              <div className="p-8 text-center text-xs text-muted-foreground italic bg-zinc-900/50 rounded-xl border border-white/10">
                Nenhuma sugestão de demanda vinculada a esta sessão.
              </div>
            ) : (
              relatedSuggestions.map((sug) => {
                const isExpanded = expandedSugId === sug.id;
                return (
                  <div
                    key={sug.id}
                    className={cn(
                      "rounded-xl border transition-all bg-zinc-900 overflow-hidden",
                      isExpanded ? "border-purple-500/50 shadow-lg shadow-purple-500/5" : "border-white/10 hover:border-white/20"
                    )}
                  >
                    {/* Header */}
                    <div
                      onClick={() => setExpandedSugId(isExpanded ? null : sug.id)}
                      className="p-4 flex items-center justify-between cursor-pointer select-none"
                    >
                      <div className="flex items-center gap-3">
                        <Badge
                          variant="outline"
                          className={cn(
                            "text-[10px] uppercase font-bold px-2 py-0.5",
                            sug.suggested_type === "AJUSTE_DEMANDA"
                              ? "bg-amber-500/10 text-amber-300 border-amber-500/30"
                              : "bg-emerald-500/10 text-emerald-300 border-emerald-500/30"
                          )}
                        >
                          {sug.suggested_type === "AJUSTE_DEMANDA" ? "Ajuste" : "Nova Demanda"}
                        </Badge>
                        <h4 className="text-xs font-bold text-zinc-100">{sug.suggested_title}</h4>
                      </div>

                      <div className="flex items-center gap-3">
                        <span className="text-[11px] text-muted-foreground flex items-center gap-1 font-mono">
                          <Clock className="h-3 w-3 text-purple-400" /> ~{sug.estimated_hours || 2}h
                        </span>
                        {isExpanded ? (
                          <ChevronUp className="h-4 w-4 text-zinc-400" />
                        ) : (
                          <ChevronDown className="h-4 w-4 text-zinc-400" />
                        )}
                      </div>
                    </div>

                    {/* Briefing detalhado */}
                    {isExpanded && (
                      <div className="px-4 pb-4 pt-1 border-t border-white/5 space-y-3 bg-black/20">
                        <div className="space-y-1">
                          <span className="text-[10px] uppercase font-bold text-purple-400 tracking-wider">
                            Briefing Estruturado da IA
                          </span>
                          <div className="bg-zinc-950 p-3.5 rounded-lg border border-white/5 text-xs text-zinc-200 leading-relaxed font-sans">
                            <MarkdownView content={sug.suggested_description || "Sem briefing adicional."} />
                          </div>
                        </div>

                        <div className="flex items-center justify-between pt-2 border-t border-white/5">
                          <Button
                            type="button"
                            variant="ghost"
                            size="sm"
                            onClick={() => handleDismiss(sug.id)}
                            className="h-8 text-xs text-zinc-400 hover:text-red-300 hover:bg-red-500/10 gap-1 cursor-pointer"
                          >
                            <XCircle className="h-3.5 w-3.5" /> Descartar esta sugestão
                          </Button>

                          {sug.status === "approved" ? (
                            <Badge variant="outline" className="bg-emerald-500/10 text-emerald-300 border-emerald-500/30 text-xs">
                              <CheckCircle2 className="h-3.5 w-3.5 mr-1" /> Aprovada (Criada em Rascunho)
                            </Badge>
                          ) : (
                            <Button
                              type="button"
                              size="sm"
                              onClick={() => handleApprove(sug.id)}
                              className="h-8 text-xs bg-purple-600 hover:bg-purple-700 text-white gap-1.5 font-semibold cursor-pointer shadow-md shadow-purple-600/20"
                            >
                              <CheckCircle2 className="h-4 w-4" />
                              Aprovar & Criar Demanda
                            </Button>
                          )}
                        </div>
                      </div>
                    )}
                  </div>
                );
              })
            )}
          </TabsContent>

          {/* 3. ANOTAÇÕES MANUAIS */}
          <TabsContent value="notes" className="flex-1 min-h-0 mt-3">
            <div className="h-full rounded-xl bg-black/40 border border-white/10 p-5 overflow-y-auto">
              <Textarea
                readOnly
                value={manualNotesText || "Nenhuma anotação manual registrada durante esta reunião."}
                className="w-full h-full bg-transparent border-none text-xs text-zinc-200 resize-none leading-relaxed font-sans focus-visible:ring-0 p-0"
              />
            </div>
          </TabsContent>

          {/* 4. TRANSCRIÇÃO BRUTA */}
          <TabsContent value="transcript" className="flex-1 min-h-0 mt-3">
            <Textarea
              readOnly
              value={transcriptContent}
              className="w-full h-full min-h-[220px] bg-black/40 border-white/10 text-xs font-mono resize-none leading-relaxed"
            />
          </TabsContent>
        </Tabs>
      </DialogContent>
    </Dialog>
  );
}
