/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated.index'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated.admin'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated.agenda'
import { Route as AuthenticatedCrmRouteImport } from './routes/_authenticated.crm'
import { Route as AuthenticatedFinanceRouteImport } from './routes/_authenticated.finance'
import { Route as AuthenticatedInboxRouteImport } from './routes/_authenticated.inbox'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated.profile'
import { Route as PortalSlugRouteImport } from './routes/portal.$slug'
import { Route as AuthenticatedClientsIndexRouteImport } from './routes/_authenticated.clients.index'
import { Route as AuthenticatedClientsIdRouteImport } from './routes/_authenticated.clients.$id'
import { Route as AuthenticatedClientsNewRouteImport } from './routes/_authenticated.clients.new'
import { Route as ApiPublicCaptureRouteImport } from './routes/api/public/capture'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedCrmRoute = AuthenticatedCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFinanceRoute = AuthenticatedFinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInboxRoute = AuthenticatedInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const PortalSlugRoute = PortalSlugRouteImport.update({
  id: '/portal/$slug',
  path: '/portal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedClientsIndexRoute =
  AuthenticatedClientsIndexRouteImport.update({
    id: '/clients/',
    path: '/clients/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedClientsIdRoute = AuthenticatedClientsIdRouteImport.update({
  id: '/clients/$id',
  path: '/clients/$id',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClientsNewRoute = AuthenticatedClientsNewRouteImport.update({
  id: '/clients/new',
  path: '/clients/new',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const ApiPublicCaptureRoute = ApiPublicCaptureRouteImport.update({
  id: '/api/public/capture',
  path: '/api/public/capture',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/portal/$slug': typeof PortalSlugRoute
  '/clients/$id': typeof AuthenticatedClientsIdRoute
  '/clients/new': typeof AuthenticatedClientsNewRoute
  '/api/public/capture': typeof ApiPublicCaptureRoute
  '/clients/': typeof AuthenticatedClientsIndexRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/crm': typeof AuthenticatedCrmRoute
  '/finance': typeof AuthenticatedFinanceRoute
  '/inbox': typeof AuthenticatedInboxRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/portal/$slug': typeof PortalSlugRoute
  '/': typeof AuthenticatedIndexRoute
  '/clients/$id': typeof AuthenticatedClientsIdRoute
  '/clients/new': typeof AuthenticatedClientsNewRoute
  '/api/public/capture': typeof ApiPublicCaptureRoute
  '/clients': typeof AuthenticatedClientsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/crm': typeof AuthenticatedCrmRoute
  '/_authenticated/finance': typeof AuthenticatedFinanceRoute
  '/_authenticated/inbox': typeof AuthenticatedInboxRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/portal/$slug': typeof PortalSlugRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/clients/$id': typeof AuthenticatedClientsIdRoute
  '/_authenticated/clients/new': typeof AuthenticatedClientsNewRoute
  '/api/public/capture': typeof ApiPublicCaptureRoute
  '/_authenticated/clients/': typeof AuthenticatedClientsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/agenda'
    | '/crm'
    | '/finance'
    | '/inbox'
    | '/profile'
    | '/portal/$slug'
    | '/clients/$id'
    | '/clients/new'
    | '/api/public/capture'
    | '/clients/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/agenda'
    | '/crm'
    | '/finance'
    | '/inbox'
    | '/profile'
    | '/portal/$slug'
    | '/'
    | '/clients/$id'
    | '/clients/new'
    | '/api/public/capture'
    | '/clients'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/agenda'
    | '/_authenticated/crm'
    | '/_authenticated/finance'
    | '/_authenticated/inbox'
    | '/_authenticated/profile'
    | '/portal/$slug'
    | '/_authenticated/'
    | '/_authenticated/clients/$id'
    | '/_authenticated/clients/new'
    | '/api/public/capture'
    | '/_authenticated/clients/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  PortalSlugRoute: typeof PortalSlugRoute
  ApiPublicCaptureRoute: typeof ApiPublicCaptureRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/crm': {
      id: '/_authenticated/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof AuthenticatedCrmRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/finance': {
      id: '/_authenticated/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof AuthenticatedFinanceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inbox': {
      id: '/_authenticated/inbox'
      path: '/inbox'
      fullPath: '/inbox'
      preLoaderRoute: typeof AuthenticatedInboxRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/portal/$slug': {
      id: '/portal/$slug'
      path: '/portal/$slug'
      fullPath: '/portal/$slug'
      preLoaderRoute: typeof PortalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/clients/': {
      id: '/_authenticated/clients/'
      path: '/clients'
      fullPath: '/clients/'
      preLoaderRoute: typeof AuthenticatedClientsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clients/$id': {
      id: '/_authenticated/clients/$id'
      path: '/clients/$id'
      fullPath: '/clients/$id'
      preLoaderRoute: typeof AuthenticatedClientsIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/clients/new': {
      id: '/_authenticated/clients/new'
      path: '/clients/new'
      fullPath: '/clients/new'
      preLoaderRoute: typeof AuthenticatedClientsNewRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/capture': {
      id: '/api/public/capture'
      path: '/api/public/capture'
      fullPath: '/api/public/capture'
      preLoaderRoute: typeof ApiPublicCaptureRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedCrmRoute: typeof AuthenticatedCrmRoute
  AuthenticatedFinanceRoute: typeof AuthenticatedFinanceRoute
  AuthenticatedInboxRoute: typeof AuthenticatedInboxRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedClientsIdRoute: typeof AuthenticatedClientsIdRoute
  AuthenticatedClientsNewRoute: typeof AuthenticatedClientsNewRoute
  AuthenticatedClientsIndexRoute: typeof AuthenticatedClientsIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedCrmRoute: AuthenticatedCrmRoute,
  AuthenticatedFinanceRoute: AuthenticatedFinanceRoute,
  AuthenticatedInboxRoute: AuthenticatedInboxRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedClientsIdRoute: AuthenticatedClientsIdRoute,
  AuthenticatedClientsNewRoute: AuthenticatedClientsNewRoute,
  AuthenticatedClientsIndexRoute: AuthenticatedClientsIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  PortalSlugRoute: PortalSlugRoute,
  ApiPublicCaptureRoute: ApiPublicCaptureRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
